// <auto-generated />
using System;
using DosyaTakipSistemi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DosyaTakipSistemi.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DosyaTakipSistemi.Models.DosyaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EsasNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HarcDurumu")
                        .HasColumnType("bit");

                    b.Property<string>("KararNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KararTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("KararTebligTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mahkeme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("kararTur")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Dosyalar");
                });

            modelBuilder.Entity("DosyaTakipSistemi.Models.TarafModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DosyaId")
                        .HasColumnType("int");

                    b.Property<bool>("IstinafTalebi")
                        .HasColumnType("bit");

                    b.Property<string>("TarafTur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TebligTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TemyizTalebi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DosyaId");

                    b.ToTable("Taraflar");
                });

            modelBuilder.Entity("DosyaTakipSistemi.Models.TarafModel", b =>
                {
                    b.HasOne("DosyaTakipSistemi.Models.DosyaModel", "Dosya")
                        .WithMany("Taraflar")
                        .HasForeignKey("DosyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dosya");
                });

            modelBuilder.Entity("DosyaTakipSistemi.Models.DosyaModel", b =>
                {
                    b.Navigation("Taraflar");
                });
#pragma warning restore 612, 618
        }
    }
}
